export const contentData = {
  companiesData: [
    {
      uid: 'zervant',
      cvrNumber: '12345678',
      companyName: 'Zervant',
      address: 'Keilaranta 17C',
      postNoCity: 'FI-02150 ESPOO',
      companyType: 'Limited company',
      status: 'Active',
    },
    {
      uid: 'kontist',
      cvrNumber: '12345678',
      companyName: 'Kontist',
      address: 'Kastanienallee 98B',
      postNoCity: '10435 Berlin',
      companyType: 'GmbH',
      status: 'Active',
    },
    {
      uid: 'billy',
      cvrNumber: '12345678',
      companyName: 'Billy',
      address: 'Vesterbrogade 1C, 6.',
      postNoCity: '1620 København V',
      companyType: 'Limited Liability Company',
      status: 'Active',
    },
    {
      uid: 'tellow',
      cvrNumber: '12345678',
      companyName: 'Tellow',
      address: 'Danzigerkade 207',
      postNoCity: '1013 AP Amsterdam',
      companyType: 'Limited company',
      status: 'Active',
    },
    {
      uid: 'salary',
      cvrNumber: '12345678',
      companyName: 'Salary',
      address: 'Vesterbrogade 1E, 6.',
      postNoCity: '1620 København V',
      companyType: 'Limited Liability Company',
      status: 'Active',
    },
    {
      uid: 'ageras-finance',
      cvrNumber: '12345678',
      companyName: 'Ageras Finance',
      address: 'Vesterbrogade 1E, 6.',
      postNoCity: '1620 København V',
      companyType: 'Limited Liability Company',
      status: 'Active',
    },
  ],
}
