// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  company: dynamic(() => import("./Company")),
  placeholder: dynamic(() => import("./Placeholder")),
  virkepedia: dynamic(() => import("./Virkepedia")),
};
